config/routes.rb
Webistar::Application.routes.draw do
  root :to => 'homepages#index'
  devise_for :users

  resources :rater
  resources :homepages do
    post :contact, :on => :collection
  end
  resources :galleries
  resources :comments
  resources :sliders
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :title, :email, :body
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  letsrate_rateable "name"
  attr_accessible :image, :name
  has_attached_file :image, :styles => { :thumb => "x150" }, :default_url => "/images/:style/missing.png"
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :gallery

  attr_accessible :gallery_id, :stars
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  attr_accessible :activity, :description, :priority, :image
  has_attached_file :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  letsrate_rater
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'net/http'
  protect_from_forgery

  protected
  RECAPTCHA_PRIVATE_KEY = '6Lfg1d4SAAAAAOJrSiqQeZecrhtdfACkzxyyibdm'

  def verify_recaptcha(remote_ip, params)
    responce = Net::HTTP.post_form(URI.parse('http://www.google.com/recaptcha/api/verify'),
                                   {'privatekey'=>RECAPTCHA_PRIVATE_KEY, 'remoteip'=>remote_ip, 'challenge'=>params[:recaptcha_challenge_field], 'response'=> params[:recaptcha_response_field]})
    result = {:status => responce.body.split("\n")[0], :error_code => responce.body.split("\n")[1]}

    if result[:error_code] == "incorrect-captcha-sol"
      flash[:alert] = "The CAPTCHA solution was incorrect. Please re-try"
    elsif
    flash[:alert] = "There has been a unexpected error with the application. Please contact the administrator. error code: #{result[:error_code]}"
    end
    result
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :json
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @comment = Comment.new params[:comment]
    raise params.inspect
    if verify_recaptcha(request.remote_ip, params)[:status] == 'false'

      respond_with @comment
    else
      respond_with @comment if @comment.save
    end
  end

  def update
  end

  def destroy
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  respond_to :json
  def index
    @gallery = Gallery.all
    gallery  = @gallery.map{|img| img[:path] = img.image.url(:thumb); img[:averange] = Rate.average(:stars,:conditions => ["gallery_id=?", img.id]).to_f.round(1) }
    respond_with @gallery
  end

  def show
    respond_with  Gallery.find(params[:id])
  end

  def create
    @gallery = Gallery.create!(params[:galleries])
    redirect_to "/#gallery"
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  respond_to :json

  def index

  end

  def show
  end

  def edit
  end

  def new
    @comment  = Comment.new
  end

  def create
  end

  def update
  end

  def destroy
  end


  def contact
    Contact.contact_email(params).deliver
    render :json => true
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController 
  
  def create
    rate = Rate.create(gallery_id: params[:id], stars: params[:score])
    average = Rate.average(:stars,:conditions => ["gallery_id=?", params[:id]]).to_f.round(1)


    render :json => average
  end
end

app/controllers/sliders_controller.rb
class SlidersController < ApplicationController
  def index
    @sliders  = Slider.all
  end

  def show
    @slider  = Slider.find(params[:id])
  end

  def new
    @slider = Slider.new
  end

  def edit
    @slider = Slider.find( params[:id] )
  end

  def create
    @slider = Slider.new(params[:slider])
    @slider.save
    redirect_to @slider
  end

  def update
    @slider = Slider.update(params[:id],params[:slider])
    redirect_to @slider
  end

  def destroy
    @slider = Slider.find(params[:id])
    @slider.destroy
    redirect_to sliders_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/slider_helper.rb
module SliderHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/views/comments/create.html.haml
%h1 Comments#create
%p Find me in app/views/comments/create.html.haml

app/views/comments/destroy.html.haml
%h1 Comments#destroy
%p Find me in app/views/comments/destroy.html.haml

app/views/comments/edit.html.haml
%h1 Comments#edit
%p Find me in app/views/comments/edit.html.haml

app/views/comments/index.html.haml
%h1 Comments#index
%p Find me in app/views/comments/index.html.haml

app/views/comments/new.html.haml
%h1 Comments#new
%p Find me in app/views/comments/new.html.haml

app/views/comments/show.html.haml
%h1 Comments#show
%p Find me in app/views/comments/show.html.haml

app/views/comments/update.html.haml
%h1 Comments#update
%p Find me in app/views/comments/update.html.haml

app/views/contact/contact_email.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
</head>
<body>
<h1>Welcome from <%= @name %></h1>
<%= @desc %>
</body>
</html>

app/views/galleries/index.html.haml
=#render 'homepages/header'
%div.contents
  %div#block.block

  %script{:type=>"text/javascript", :id=>'menu'}
    %div.shadow-menu
    %div.menu
      %ul
        %li#active
          =link_to 'главная', "#", :class => 'menu-item', :rel => 'home'
        %li
          =link_to 'галерея', '#', :class => 'menu-item', :rel => 'galleries'
        %li
          =link_to 'контакти', "#", :class => 'menu-item', :rel => 'contact'

  %script{type:"text/javascript", id:'start'}
    %div{ class:"start" }
      START


  =render 'homepages/contact'

  %script{:type=>"text/javascript", :id=>'success'}
    //<!--[CDATA[
    %div.success
      Пользователь <%= username %> найден.
      %a{:href=>'#!/'}Go back
    //]]-->

app/views/galleries/show.html.haml
%h1 Gallery#show
%p Find me in app/views/galleries/show.html.haml

app/views/homepages/_header.html.haml
%div.block-header
	%div
%div.block-menu
-# %div.shadow-menu
-# %div.menu
-# 	%ul
-# 		%li#active
-# 			=#link_to 'главная', root_path, :class => 'menu-item', :rel => 'main'
-# 		%li
-# 			=#link_to 'галерея', '/', :class => 'menu-item', :rel => 'galleries'
-# 		%li
-# 			=#link_to 'контакти', '/', :class => 'menu-item', :rel => 'contact'

app/views/homepages/_last_work.html.haml
%div.content
  =link_to 	'&#9668;'.html_safe, '', :class => :prev, :id => 'cs-prev'
  %div.gallery
    %ul
      %li
        =image_tag 'works/1.jpg', :style=>'width:150px;height:113px', :alt=>1
      %li
        =image_tag 'works/2.jpg', :style=>'width:150px;height:113px', :alt=>2
      %li
        =image_tag 'works/3.jpg', :style=>'width:150px;height:113px', :alt=>3
      %li
        =image_tag 'works/4.jpg', :style=>'width:150px;height:113px', :alt=>4
  =link_to 	'&#9658;'.html_safe, '', :class => :next, :id => 'cs-next'

app/views/homepages/_menu.html.haml
%div.shadow-menu
%div.menu
  %ul
    %li#active
      =link_to 'главная', "#", :class => 'menu-item', :rel => 'home'
    %li
      =link_to 'галерея', '#gallery', :class => 'menu-item', :rel => 'galleries'
    %li
      =link_to 'контакти', "#contact", :class => 'menu-item', :rel => 'contact'

app/views/homepages/index.html.haml
=render 'header'
%div.contents
  %div#blocks
  =#render 'slider'
  =#render 'last_work'
  %div#1footer


  %div#contents
  =#render 'homepages/contact'

app/views/homepages/new.html.haml
= form_for @comment, :url => homepages_url do |f|
  .field
    = f.label :title
    %br/
    = f.text_area :title
  .field
    = f.label :email
    %br/
    = f.email_field :email
  .field
    = f.label :body
    %br/
    = f.text_area :body
  #captcha
    = javascript_include_tag "http://www.google.com/recaptcha/api/challenge?k=6Lfg1d4SAAAAAOo3i_WYogIksf1Y2MPAhJfRaPnB"
    %noscript
      %iframe{:frameborder => "0", :height => "300", :src => "http://www.google.com/recaptcha/api/noscript?k=6Lfg1d4SAAAAAOo3i_WYogIksf1Y2MPAhJfRaPnB", :width => "500"}
      %textarea{:cols => "40", :name => "recaptcha_challenge_field", :rows => "3"}
      %input{:name => "recaptcha_response_field", :type => "hidden", :value => "manual_challenge"}
  .actions
    = f.submit

app/views/layouts/_header.html.haml
%div.header
	%div#star-logo
	%div#shadow

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title WebIStar
    = stylesheet_link_tag :application
    = javascript_include_tag :application

    = csrf_meta_tag
  %body
    %div#body
      =render 'layouts/header'
      %div.block
        =render 'homepages/menu'
        = yield

app/views/sliders/_form.html.haml
= form_for @slider, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :priority, :class => 'control-label'
    .controls
      = f.number_field :priority, :class => 'number_field'
  .control-group
    = f.label :activity, :class => 'control-label'
    .controls
      = f.check_box :activity, :class => 'check_box'
  .control-group
    = f.label :image, :class => 'control-label'
    .controls
      = f.file_field :image, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), sliders_path, :class => 'btn'

app/views/sliders/edit.html.haml
- model_class = Slider
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/sliders/index.html.haml
- model_class = Slider
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:priority)
      %th= model_class.human_attribute_name(:activity)
      %th= model_class.human_attribute_name(:image_file_name)
      %th= model_class.human_attribute_name(:image_content_type)
      %th= model_class.human_attribute_name(:image_file_size)
      %th= model_class.human_attribute_name(:image_updated_at)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @sliders.each do |slider|
      %tr
        %td= link_to slider.id, slider_path(slider)
        %td= slider.description
        %td= slider.priority
        %td= slider.activity
        %td= slider.image_file_name
        %td= slider.image_content_type
        %td= slider.image_file_size
        %td= slider.image_updated_at
        %td=l slider.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_slider_path(slider), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), slider_path(slider), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_slider_path, :class => 'btn btn-primary'

app/views/sliders/new.html.haml
- model_class = Slider
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/sliders/show.html.haml
- @slider = Slider.first
- model_class = Slider
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @slider.description
%p
  %strong= model_class.human_attribute_name(:priority) + ':'
  %br
  = @slider.priority
%p
  %strong= model_class.human_attribute_name(:activity) + ':'
  %br
  = @slider.activity
%p
  %strong= model_class.human_attribute_name(:image_file_name) + ':'
  %br
  = @slider.image_file_name
%p
  %strong= model_class.human_attribute_name(:image_content_type) + ':'
  %br
  = @slider.image_content_type
%p
  %strong= model_class.human_attribute_name(:image_file_size) + ':'
  %br
  = @slider.image_file_size
%p
  %strong= model_class.human_attribute_name(:image_updated_at) + ':'
  %br
  = @slider.image_updated_at

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), sliders_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_slider_path(@slider), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), slider_path(@slider), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'